### ISSUE TITLE
--insecure - Missing in version 1.1

### ISSUE THREAD

**Issue by TPuschl** [xWyatt/check_rest_api#12]
Hi,

it looks like that in the latest version 1.1 the flag "--insecur / -k" is missing as it doesn't work.
Also ./check_rest_api --help doesn't show anything about this flag compared to the readme here on gtihub.
Can you please implement this flag again, as I would need that to use this script as some of our internal APIs have no valid SSL cert.

Thx

**Comment by xWyatt** [comment]
Good catch! I forgot to add that option to the program help text. It still existed and was able to be used in v1.1.0 but I went ahead and just created a new release anyway.

If you download v1.1.1 you should see that option now in the usage text.

Thanks!
W
