### ISSUE TITLE
Include API Method

### ISSUE THREAD

**Issue by TPuschl** [xWyatt/check_rest_api#13]
Hi,
right now the script uses only the Method GET. We have now some API-Calls which requires instead of GET a POST Method.
In our case no further parameters are needed. The return data is in json format an contains only "value: 12345".
Would be great to add a parameter where it can be switched between GET and POST.
Thx

**Comment by xWyatt** [comment]
Do you also need to _send_ data in the body of the POST request or are all the API parameters in the URI?

It sounds like the latter but I want to double check before working on this.

W

**Comment by TPuschl** [comment]
Hi,

all Parameters are in the URI, so right now not data in body is needed but maybe in the future. So if you prepare it also which such a possibility it would be great.

Thomas
