### ISSUE TITLE
Add support to return optional performance data

### ISSUE THREAD

**Issue by levelsw** [xWyatt/check_rest_api#17]
It would be great if it is possible to return performance data. I would like to create a graph of the return value. Nagios just needs a specific syntax in the return value for that (https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/perfdata.html). Is this possible? 

I tried searching if I could somehow modify the return value so that Nagios uses it as performance data but don't see an easy way to do that from my side.

Thanks!

Wesley

**Comment by xWyatt** [comment]
This has been added with the latest release 1.2.0. Thanks for the suggestion!

https://github.com/xWyatt/check_rest_api/releases/tag/v1.2.0
