### ISSUE TITLE
how to auth using --negotiate

### ISSUE THREAD

**Issue by hs-hub-world** [xWyatt/check_rest_api#18]
for example with curl, we use --negotiate, can we do the same with check_rest_api -?

 curl https://server/92936TAJ1 --negotiate -u coolUser

Thanks!
H

**Comment by xWyatt** [comment]
Unfortunately I'm not familiar with Kerberos/GSS authentication via CURL nor do I have an environment to test this with.

If you can send me the headers CURL is sending to your server when using that command with _and_ without the `--negotiate` flag I may be able to add something. I would need you to test it out for me before I publish though.
