### ISSUE TITLE
Option --insecure not working

### ISSUE THREAD

**Issue by Gianni-Caselli** [xWyatt/check_rest_api#9]
Hi,

I tried to use the option -k or --insecure but it' doesn't work:

check_rest_api -H https://example.com/api/ -b 'user:pass' --insecure
UNKNOWN - cURL call resulted in error: Peer certificate cannot be authenticated with given CA certificates

check_rest_api -H https://example.com/api/ -b 'user:pass'
UNKNOWN - cURL call resulted in error: Peer certificate cannot be authenticated with given CA certificates

The command has no change with the --insecure option added (with the -k is the same)

Can you help me?
I donwloaded the script from here [Release 1.0.0](https://github.com/xWyatt/check_rest_api/releases/tag/v1.0.0)

Br.

**Comment by xWyatt** [comment]
Oops, this was a bug. I've fixed it an re-released with version 1.0.1.

Download that and give it a shot; if `--insecure`/`-k` still doesn't work let me know.

Thanks!
W
